apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-test
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: cron-test
        spec:
          restartPolicy: OnFailure
          containers:
          - name: alpine
            image: alpine
            command: ["/sbin/apk", "add", "curl", "&&", "/usr/bin/curl", "https://lk.rebrainme.com/kubernetes/report"]