---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-dp
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cr-dp
rules:
- apiGroups: [""]
  resources: ["deployments"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sa-dp-cr-dp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cr-dp 
subjects:
- kind: ServiceAccount
  name: sa-dp
  namespace: default 

