apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginxconfig
      mountPath: "/etc/nginx/nginx.conf"
      subPath: nginx.conf
      readOnly: true
    env:
      - name: nginx-env
        valueFrom:
          secretKeyRef:
            name: nginx-env
            key: AUTH 
  volumes:
  - name: nginxconfig
    configMap:
        name: nginx-conf
