---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: results.study.rebrainme.com
spec:
  group: study.rebrainme.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                task:
                  type: string
                result:
                  type: string
  scope: Namespaced
  names:
    plural: results
    singular: result
    kind: Rerult
    shortNames:
    - res
---
apiVersion: study.rebrainme.com/v1
kind: Rerult
metadata:
  name: result1
spec:
  task: Simple Task
  result: Some result  