---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: local-http
  namespace: default
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 8080