---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-dp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd-dp
  template:
    metadata:
      labels:
        app: httpd-dp
    spec:
      containers:
        - name: httpd
          image: httpd:latest
---
apiVersion: v1
kind: Service
metadata:
 name: nginx-svc-int
spec:
 type: ClusterIP
 selector:
    app: httpd-dp
 ports:
 - port: 80
   targetPort: 80   
---
apiVersion: v1
kind: Service
metadata:
 name: nginx-svc-ext
spec:
 type: LoadBalancer
 selector:
    app: httpd-dp
 ports:
 - port: 80
   targetPort: 80             