---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  # selfSigned:
  #   crlDistributionPoints:
  #   - "http://example.com"
  acme:
    email: k.keker@ya.ru
    privateKeySecretRef:
      name: letsencrypt-private-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
       ingress:
         class: nginx

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-own-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
  - host: dickpic.kkeker.2ek.org
  tls:
  - hosts:
    - dickpic.kkeker.2ek.org
    secretName: my-test-acme