---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-dp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami-dp
  template:
    metadata:
      labels:
        app: whoami-dp
    spec:
      containers:
        - name: whoami
          image: bee42/whoami
          ports:
            - containerPort: 80
              name: web
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: whoami-monitor
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: whoami-dp
  podMetricsEndpoints:
  - port: web              
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-whoami
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: whoami-dp
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Pods
    pods:
      metricName: http_requests
      targetAverageValue: 1000m