---
apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    app: redis-pod
spec:
  containers:
  - name: redis
    image: redis
    ports:
      - containerPort: 6379
        name: redis-server
  - name: redis-exporter
    #image: oliver006/redis_exporter
    image: bitnami/redis-exporter
    ports:
      - containerPort: 9121
        name: redis-exporter
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: redis-monitor
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: redis-pod
  podMetricsEndpoints:
  - port: redis-exporter

