---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{.Values.ingress.name}}
spec:
  rules:
  - host: {{.Values.ingress.host}}
    http:
      paths:
      - path: {{.Values.ingress.path}}
        backend:
          serviceName: {{.Values.service.name}}
          servicePort: {{.Values.ingress.port}}